language: python
sudo: false
python:
- "3.7-dev"
- "3.6"
install:
  - pip install tox-travis
  - pip install codecov

script: tox
after_success: codecov
before_script:
  - psql -c 'create database georangefilter;' -U postgres
services:
  - postgresql
